name: whatsapp_stickers_plus
description: WhatsApp Stickers plugin for Flutter.
version: 1.1.1
homepage: https://github.com/anderscheow/whatsapp_stickers_plus

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: dev.applicazza.flutter.plugins.whatsapp_stickers_plus
        pluginClass: WhatsappStickersPlugin
      ios:
        pluginClass: WhatsappStickersPlugin
